version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production